pipeline {
    agent any
    stages {
        stage('Delete the workspace') {
            steps {
                sh "rm -rf $WORKSPACE/*"
            }
        }
        stage('Second Stage') {
            steps {
                echo "Second stage"
            }
        }
        stage('Third Stage') {
            steps {
                echo "Third stage"
            }
        }
    }
}