pipeline {
    agent any
    environment {
        WORKSPACE = "/chef-repo/workspace/chef-pipeline"
    }
    stages {
        stage('Delete the workspace') {
            steps {
                echo "*** workspace1 $WORKSPACE"
                echo "*** workspace2 ${env.WORKSPACE}"
                sh "sudo rm -rf $WORKSPACE/*"
            }
        }
        stage('Download Workshop') {
            steps {
                git credentialsId: 'git-repo-creds', url: 'https://github.com/pocsteve/workshops.git'
            }
        }
        stage('Lint Testing') {
            steps {
                echo '*** Lint Testing ***'
                sh 'sudo cookstyle .'
                dir("$WORKSPACE/cookbooks") {
                    sh 'sudo foodcritic . -t ~FC078'
                }
            }
        }
        stage('Unit Testing') {
            steps {
                echo '*** Unit Testing ***'
                dir("$WORKSPACE/cookbooks/tomcat") {
                   sh 'sudo chef exec rspec spec/unit/recipes/default_spec.rb'
                }
            }
        }
        stage('Functional Testing') {
            steps {
                dir("$WORKSPACE/cookbooks") {
                    echo '*** Building Policyfile ***'
                    sh 'sudo chef install ../policyfiles/workshop.rb'
                    echo '*** Running Test Kitchen ***'
                    sh 'sudo kitchen verify'
                    sh 'sudo kitchen converge'
                    sh 'sudo kitchen verify'
                    sh 'sudo kitchen destroy'
                }
            }
        }
        stage('Upload to Chef Server') {
            steps {
                dir("$WORKSPACE/policyfiles") {
                    echo '*** Uploading Policy to Chef Server ***'
                    sh 'sudo chef push sandbox workshop.lock.json'
                }
            }
        }
    }
}
