pipeline {
    agent any
    stages {
        stage('Delete the workspace') {
            steps {
                sh "rm -rf $WORKSPACE/*"
            }
        }
        stage('Download MongoDB') {
            steps {
                git credentialsId: 'git-repo-creds', url: 'https://github.com/pocsteve/workshops.git'
            }
        }
        stage('MongoDB Kitchen Test') {
            steps {
                cd "$WORKSPACE/cookbooks/mongodb"
                sh 'kitchen test''
            }
        }
    }
}